# Generated by Django 5.1.1 on 2024-09-27 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0002_alter_sellers_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge',
            name='amount',
            field=models.PositiveIntegerField(),
        ),
    ]
