# Generated by Django 5.1.1 on 2024-09-27 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargerequests',
            name='amount',
            field=models.PositiveIntegerField(),
        ),
    ]
